backend/controllers/AsCountryController.php
<?php

namespace backend\controllers;

use common\modules\ApiAlphaStrah\models\Country2dict;
use common\modules\ApiAlphaStrah\models\Regions;
use kartik\grid\EditableColumnAction;
use Yii;
use common\modules\ApiAlphaStrah\models\Country;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CountryController implements the CRUD actions for Country model.
 */
class AsCountryController extends Controller
{
	public function actions()
	{
		return ArrayHelper::merge(parent::actions(), [
			'editbook' => [                                       // identifier for your editable column action
				'class' => EditableColumnAction::className(),     // action class name
				'modelClass' => Country::className(),                // the model for the record being edited
				'showModelErrors' => true,                        // show model validation errors after save
				'errorOptions' => ['header' => '']                // error summary HTML options
			]
		]);
	}

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

	public function actionSaveVisa(){
		$checked    = Yii::$app->request->post('checked', 0);
		$country_id = Yii::$app->request->post('country_id', false);

		if ($country_id) {
			$model = Country::findOne(['countryID'=>$country_id]);
			if ($model) {
				$model->visa = $checked;
				$model->save();
			}
		}
	}

    /**
     * Lists all Country models.
     * @return mixed
     */
    public function actionIndex()
    {
	    if (Yii::$app->request->post('hasEditable')) {
		    // instantiate your book model for saving
		    $id = Yii::$app->request->post('editableKey');
		    $model = Country::findOne($id);

		    // store a default json response as desired by editable
		    $out = Json::encode(['output'=>'', 'message'=>'']);
		    $posted = current($_POST['Country']);
		    $post = ['Country' => $posted];
		    if ($model->load($post)) {
			    // can save model or do something before saving model
			    $model->save();
			    $output = '';
			    $out = Json::encode(['output'=>$output, 'message'=>'']);
		    }
		    // return ajax json encoded response and exit
		    echo $out;
		    return;
	    }

        $dataProvider = new ActiveDataProvider([
            'query' => Country::find()->indexBy('countryID'),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Country models.
     * @return mixed
     */
    public function actionUpdate($id)
    {
	    $model = Country::findOne($id);
	    if ($model->load(Yii::$app->request->post()) && $model->save()) {
	    	Country2dict::deleteAll(['api_id' => $id]);
	    	$data = Yii::$app->request->post('GeoCountry');
	    	foreach($data as $oneId){
	    		if ($oneId) {
				    $geoModel = new Country2dict();
				    $geoModel->api_id = $id;
				    $geoModel->internal_id = $oneId;
				    $geoModel->save();
			    }
		    }
	    	$this->redirect(['index']);
	    }

        return $this->render('update', [
            'model' => $model,
            'id' => $id,
        ]);
    }

    public function actionImport()
    {
    	$updated = $inserted = $deleted = 0;
	    $ids = [];
	    $countries = Yii::$app->getModule('ApiAlphaStrah')->getCountries();
	    foreach($countries as $country){
	    	$model = Country::find()->where(['countryID' => $country->countryID])->one();
	    	if (!$model){
	    		$model = New Country();
	    		$inserted++;
		    } else {
	    		$updated++;
		    }

		    /** @var $model Country */
			$model->load((array)$country, '');
			$model->enabled = 1;
			$region = Regions::findOne(['short_name'=>$country->terName]);
			$model->region_id = ($region)?$region->id: new \yii\db\Expression('NULL');
 		    if (!$model->save()) {
		    	var_dump($model->errors); die();
		    }
		    $ids[] = $model->countryID;
	    }

	    $deleted = Country::updateAll(['enabled' => 0], ['NOT IN', 'countryID', $ids]);

        return $this->render('import', [
            'updated' => $updated,
            'inserted' => $inserted,
            'deleted' => $deleted,
        ]);
    }

    /**
     * Displays a single Country model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Country model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Country the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Country::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/as-country/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model \common\modules\ApiAlphaStrah\models\Country */
/* @var $form yii\widgets\ActiveForm */
/* @var $id integer */
?>

<div class="program-form">
	<?php $form = ActiveForm::begin(); ?>

  	<?= $form->field($model, 'enabled')->dropDownList([
	    0 => 'Запрещена',
	    1 => 'Разрешена'
    ]) ?>

    <?php foreach(\common\models\GeoCountry::find()->orderBy(['name' => SORT_ASC])->all() as $country) { ?>
        <div class="col-xs-4">
          <?= \yii\bootstrap\Html::checkbox('GeoCountry[]', (bool)(bool)\common\modules\ApiAlphaStrah\models\Country2dict::find()->where(['api_id' => $id, 'internal_id' => $country->id])->count(), ['value' => $country->id, 'id' => 'country-'.$country->id]); ?>
          <?= \yii\bootstrap\Html::label($country->name, 'country-'.$country->id); ?>
        </div>
    <?php } ?>

    <div class="form-group">
      <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
    </div>
	<?php ActiveForm::end(); ?>
</div>

backend/views/as-country/import.php
<?php
/**
 * Created by PhpStorm.
 * User: miloslawsky
 * Date: 23.12.16
 * Time: 14:58
 */
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Страны';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="country-import">
  <div class="well">
	  <p>Обновлено стран: <?= $updated?></p>
	  <p>Добавлено стран: <?= $inserted?></p>
    <p>Удалено стран: <?= $deleted?></p>
  </div>
</div>

backend/views/as-country/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Страны';
$this->params['breadcrumbs'][] = $this->title;

$regions = \common\modules\ApiAlphaStrah\models\Regions::find()->orderBy(['short_name' => SORT_ASC])->all();

?>
<div class="country-index">
    <p>
        <?= Html::a(Yii::t('backend', 'Обновить список стран'), ['import'], ['class' => 'btn btn-warning']) ?>
    </p>
    <?= \kartik\grid\GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'countryID',
            // 'countryUID',
            'countryName',
            /*
            [
	            'class'=>'kartik\grid\EditableColumn',
              'attribute'=>'name',
              'pageSummary'=>true,
              'editableOptions'=> function ($model, $key, $index) {
	              return [
		              'header' => 'Локальное название',
		              'size'   => 'md',
	              ];
              }
            ],
            */
            /*
            [
	            'class'=>\kartik\grid\EditableColumn::className(),
	            'attribute'=>'parent_id',
	            'pageSummary'=>true,
              'editableOptions'=> function ($model, $key, $index) {
	              return [
		              'size'   => \kartik\popover\PopoverX::SIZE_MEDIUM,
                  'inputType' => \kartik\editable\Editable::INPUT_DROPDOWN_LIST,
                  'data' => [null => '(не задано)'] + \yii\helpers\ArrayHelper::map(\common\models\GeoCountry::find()->orderBy(['name' => SORT_ASC])->asArray()->all(), 'id', 'name'),
	              'displayValueConfig' => \yii\helpers\ArrayHelper::map(\common\models\GeoCountry::find()->asArray()->all(), 'id', 'name'),
	              ];
              }
            ],
            */
            [
              'format' => 'raw',
              'label' => 'Соответствие внутреннему справочнику',
              'value' => function($model){
                $countries = \common\modules\ApiAlphaStrah\models\Country2dict::find()->where(['api_id' => $model->countryID])->all();
                $res = [];
                foreach ($countries as $country){
                  /** @var $country \common\modules\ApiAlphaStrah\models\Country2dict */
                  $res[] = $country->geoNameModel->name;
                }
                sort($res);
                return Html::ul($res);
              }
            ],
            [
	            'class'=>\kartik\grid\EditableColumn::className(),
	            'attribute'=>'enabled',
	            'pageSummary'=>true,
              'editableOptions'=> function ($model, $key, $index) {
	              return [
		              'size'   => \kartik\popover\PopoverX::SIZE_MEDIUM,
                  'inputType' => \kartik\editable\Editable::INPUT_DROPDOWN_LIST,
                  'data' => [
	                  0 => 'Запрещена',
	                  1 => 'Разрешена'
                  ],
                  'displayValueConfig' => [
	                  0 => 'Запрещена',
	                  1 => 'Разрешена'
                  ],
	              ];
              }
            ],
            //
            // 'countryKV',
            // 'assistanteID',
            // 'assistanteUID',
            // 'assistanceCode',
            'assistanceName',
            'assistancePhones:raw',
            'terName',
            'region_id'=>  [
                'format' => 'raw',
                'label' => 'Регион',
                'value' => function($model){
                    return ($model->region)?$model->region->short_name:'';
                }
            ],
            'visa' => [
                'attribute' => 'visa',
                'format' => 'raw',
                'value' => function($model) {
                    $html = Html::beginForm('/as-country/save-visa', 'post', ['style' => 'width:50px']);
                    $html .= \yii\bootstrap\Html::hiddenInput('country_id', $model->countryID);
                    $html .= \yii\bootstrap\Html::checkbox('checked', (bool)$model->visa, [ 'class' => 'ajaxify' ]);
                    $html .= Html::endForm();
                    return $html;
                }
            ],
            'functions' => ['class' => 'yii\grid\ActionColumn','template' => '{view}{update}']],
    ]); ?>
</div>

<?php

$this->registerJs("
  $(document).on('change', '.ajaxify', function(){

    var form = $(this).parents('form');
    $(form).blur();
    var data = $(form).serializeArray();
      
    $.post($(form).attr('action'), data, function(){
      
    });  
  
  });
");

backend/views/as-country/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \common\modules\ApiAlphaStrah\models\Country */

$this->title = 'Редактировать страну: ' . $model->countryName;
$this->params['breadcrumbs'][] = ['label' => 'Страны', 'url' => ['index']];
$this->params['breadcrumbs'][] = $model->name;
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="program-update">

    <?= $this->render('_form', [
        'model' => $model,
        'id' => $id,
    ]) ?>

</div>

backend/views/as-country/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model \common\modules\ApiAlphaStrah\models\Country */

$this->title = $model->countryName;
$this->params['breadcrumbs'][] = ['label' => 'Страны', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="country-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'countryID',
            'countryUID',
            'countryName',
            'name',
            [
                'format' => 'raw',
                'label' => 'Соответствие внутреннему справочнику',
                'value' => function($model){
                    $countries = \common\modules\ApiAlphaStrah\models\Country2dict::find()->where(['api_id' => $model->countryID])->all();
                    $res = [];
                    foreach ($countries as $country){
                        /** @var $country \common\modules\ApiAlphaStrah\models\Country2dict */
                        $res[] = $country->geoNameModel->name;
                    }
                    sort($res);
                    return Html::ul($res);
                }
            ],
            'terName',
            'region_id'=>  [
                'format' => 'raw',
                'label' => 'Регион',
                'value' => function($model){
                    return ($model->region)?$model->region->short_name:'';
                }
            ],
            'countryKV',
            'assistanteID',
            'assistanteUID',
            'assistanceCode',
            'assistanceName',
            'assistancePhones',
        ],
    ]) ?>

</div>